# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import pytest
import torch

import flag_gems

from . import accuracy_utils as utils


@pytest.mark.multi_margin_loss_backward
@pytest.mark.parametrize("shape", [(2, 32), (128, 256), (512, 512)])
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
@pytest.mark.parametrize("reduction", [0, 1, 2])
@pytest.mark.parametrize("p", [1.0, 2.0])
def test_multi_margin_loss_backward(shape, dtype, reduction, p):
    N, C = shape
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    target = torch.randint(0, C, (N,), device=flag_gems.device)
    if reduction == 0:
        grad_output = torch.randn(N, dtype=dtype, device=flag_gems.device)
    else:
        grad_output = torch.rand((), dtype=dtype, device=flag_gems.device)

    ref_grad_output = utils.to_reference(grad_output)
    ref_inp = utils.to_reference(inp)
    ref_target = utils.to_reference(target)

    ref_out = torch.ops.aten.multi_margin_loss_backward(
        ref_grad_output, ref_inp, ref_target, p, 1.0, None, reduction
    )
    res_out = flag_gems.multi_margin_loss_backward(
        grad_output, inp, target, p, 1.0, None, reduction
    )
    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.multi_margin_loss_backward
@pytest.mark.parametrize("shape", [(2, 32), (128, 256)])
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
@pytest.mark.parametrize("reduction", [0, 1, 2])
@pytest.mark.parametrize("p", [1.0, 2.0])
def test_multi_margin_loss_backward_weight(shape, dtype, reduction, p):
    N, C = shape
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    target = torch.randint(0, C, (N,), device=flag_gems.device)
    weight = torch.rand(C, dtype=dtype, device=flag_gems.device)
    if reduction == 0:
        grad_output = torch.randn(N, dtype=dtype, device=flag_gems.device)
    else:
        grad_output = torch.rand((), dtype=dtype, device=flag_gems.device)

    ref_grad_output = utils.to_reference(grad_output)
    ref_inp = utils.to_reference(inp)
    ref_target = utils.to_reference(target)
    ref_weight = utils.to_reference(weight)

    ref_out = torch.ops.aten.multi_margin_loss_backward(
        ref_grad_output, ref_inp, ref_target, p, 1.0, ref_weight, reduction
    )
    res_out = flag_gems.multi_margin_loss_backward(
        grad_output, inp, target, p, 1.0, weight, reduction
    )
    utils.gems_assert_close(res_out, ref_out, dtype)
