# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils


@pytest.mark.special_psi
@pytest.mark.parametrize("shape", utils.POINTWISE_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_special_psi(shape, dtype):
    # randn covers both signs and all three code paths (reflection for x < 0.5,
    # recurrence for [0.5, 1), asymptotic for x >= 1). psi has poles at 0 and the
    # negative integers; in a narrow band around them both the reference and the
    # kernel lose precision to float32 catastrophic cancellation in pi*cot(pi*x),
    # so values within 0.05 of an integer are pushed to a benign point (the poles
    # themselves are checked separately in test_special_psi_poles).
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    near_pole = (inp - inp.round()).abs() < 0.05
    inp = torch.where(near_pole, torch.full_like(inp, 1.5), inp)
    ref_inp = utils.to_reference(inp)

    ref_out = torch.special.psi(ref_inp)
    res_out = flag_gems.special_psi(inp)

    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.special_psi
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_special_psi_poles(dtype):
    # On the poles psi matches torch.special.psi: x == 0 -> -inf, negative
    # integers -> nan. equal_nan=True lets the nan-valued poles compare equal.
    inp = torch.tensor(
        [0.0, -1.0, -2.0, -3.0, -4.0], dtype=dtype, device=flag_gems.device
    )
    ref_inp = utils.to_reference(inp)

    ref_out = torch.special.psi(ref_inp)
    res_out = flag_gems.special_psi(inp)

    utils.gems_assert_close(res_out, ref_out, dtype, equal_nan=True)
