# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def as_strided(self: torch.Tensor, size, stride, storage_offset=None) -> torch.Tensor:
    """Returns a view of the tensor with specified size, stride and storage_offset.

    This is a zero-copy view operation — the returned tensor shares storage
    with the input tensor.
    """
    logger.debug("GEMS AS_STRIDED")

    if not isinstance(self, torch.Tensor):
        raise TypeError('as_strided(): expected "self" to be a torch.Tensor')

    if storage_offset is None:
        storage_offset = self.storage_offset()

    size = tuple(size)
    stride = tuple(stride)

    if len(size) != len(stride):
        raise ValueError(
            f"size and stride must have the same length, got {len(size)} and {len(stride)}"
        )

    # Create a view by constructing a new tensor that shares the same storage.
    # Uses set_() to avoid recursion through FlagGems dispatch on torch.as_strided.
    result = torch.empty((0,), device=self.device, dtype=self.dtype)
    result.set_(self.untyped_storage(), storage_offset, size, stride)
    return result


def as_strided_(self: torch.Tensor, size, stride, storage_offset=None) -> torch.Tensor:
    """In-place version of as_strided. Modifies the tensor view metadata.

    This is a zero-copy metadata operation — no data is moved.
    """
    logger.debug("GEMS AS_STRIDED_")

    if storage_offset is None:
        storage_offset = self.storage_offset()

    size = tuple(size)
    stride = tuple(stride)

    if len(size) != len(stride):
        raise ValueError(
            f"size and stride must have the same length, got {len(size)} and {len(stride)}"
        )

    # Apply the view metadata directly to self via set_().
    # This avoids recursion through the FlagGems dispatch on self.as_strided_().
    self.set_(self.untyped_storage(), storage_offset, size, stride)
    return self
