# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

from flag_gems.ops.cumsum import cumsum_wrapper

logger = logging.getLogger(__name__)


def cumsum_(inp, dim, *, dtype=None):
    logger.debug("GEMS CUMSUM_")
    assert inp.dtype in (
        torch.float16,
        torch.float32,
        torch.bfloat16,
        torch.int16,
        torch.int32,
    ), f"cumsum_ only supports float/int dtypes, got {inp.dtype}"
    result = cumsum_wrapper(inp, dim, dtype)
    inp.copy_(result)
    return inp
