# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

from flag_gems.ops.fix import _launch_fix_kernel

logger = logging.getLogger(__name__)


def fix_(self: torch.Tensor):
    logger.debug("GEMS FIX_")
    if self.is_complex():
        # Fallback for complex dtypes not supported by Triton: use PyTorch
        return torch.trunc_(self)

    _launch_fix_kernel(self, self)
    return self
