# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "INT_TO_FLOAT")])
@triton.jit
def special_entr_func(x):
    zero = tl.zeros([], tl.float32)
    neg_inf = tl.zeros([], tl.float32) + float("-inf")
    x_fp32 = x.to(tl.float32)

    entr_positive = -x_fp32 * tl.log(x_fp32)

    result = tl.where(x_fp32 < zero, neg_inf, entr_positive)

    result = tl.where(x_fp32 == zero, zero, result)

    return result


def special_entr(A):
    logger.debug("GEMS SPECIAL_ENTR")
    return special_entr_func(A)
